final url = 'http://192.168.1.109:8080/';
final registration = url + 'register';
final login = url + 'login';
final upload = url + 'upload';
final addContent = url +'addContent';
final getContent = url + 'getContent';
final editContent = url + 'editContent';
final sendfeedback = url +'feedback';
final uploadimage = url + 'upload';
